services:
  - type: web
    name: tic-tac-toe-plus
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
